config/routes.rb
Rails.application.routes.draw do
    # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  devise_for :users
  root to: "posts#index"

  resources :users, only:[:show]

  get 'messages' => 'messages#new'
  post 'messages' => 'messages#create'
  # post 'post/:post_id/likes' => 'likes#create'
  # delete 'post/:post_id/likes' => 'likes#destroy'

  resources :posts do 
    resources :comments, only: [:create, :destroy]
    resources :likes, only: [:create, :destroy]
    collection do
      get 'search'
      get 'place'
      get 'map'
      get 'word'
      get 'about'
    end
  end


  # devise_for :users, :controllers => {
  #   :registrations => 'users/registrations',
  #   :sessions => 'users/sessions'   
  # } 

  # devise_scope :user do
  #   get "sign_in", :to => "users/sessions#new"
  #   get "sign_out", :to => "users/sessions#destroy" 
  # end
end

app/models/like.rb
class Like < ApplicationRecord
  validates :user_id, presence: true, uniqueness: {scope: :post_id}
  validates :post_id, presence: true
  belongs_to :post, counter_cache: :like_count
  belongs_to :user
  # validates_uniqueness_of :post_id, scope: :user_id


end

app/controllers/likes_controller.rb
class LikesController < ApplicationController

  before_action :set_post, only: [:create, :destroy]

  # def create
  #   @like = current_user.likes.create(like_params)
  #   respond_to do |format|
  #     format.html{redirect_to @post}
  #     format.js
  #   end

  # end

  # def destroy
  #   @like = Like.find_by(like_params, user_id: current_user.id)
  #   @like.destroy
  #   respond_to do |format|
  #     format.html { redirect_to @post }
  #     format.js
  #   end
  # end

  # private
  # def set_post
  #   @post = Post.find(params[:post_id])
  # end
  # def like_params
  #   params.permit(:post_id)
  # end
  def create
  # @like = Like.create(user_id: current_user.id, post_id: params[:post_id])
  # @likes = Like.where(post_id: params[:post_id])
  # @post = Post.find(params[:post_id])
  # @posts = Post.all
    @like = current_user.likes.create(like_params)
    @like.save!
    respond_to do |format|
      format.html { redirect_to @post }
      format.js
    end
    # redirect_to post_path(@post)
  end

  def destroy
    # @like = Like.create(user_id: current_user.id, post_id: params[:post_id])
    # @like.destroy
    # render "destroy.js.erb"
    # @likes = Like.where(post_id: params[:post_id])
    # @post = Post.find(params[:post_id])
    # @posts = Post.all
    @like = Like.find_by(like_params, user_id: current_user.id)
    @like.destroy
    respond_to do |format|
      format.html { redirect_to @post }
      format.js
    end
    # redirect_to post_path(@post)

  end

  private
  def set_post
    @post = Post.find(params[:post_id])
  end

  def like_params
    params.permit(:post_id)
  end


end

app/helpers/likes_helper.rb
module LikesHelper
end

app/views/likes/_like.html.haml
-# -if current_user.likes.find_by(post_id: @post.id)
-#   #like
-#     = link_to post_like_path(@post, current_user.likes.find_by(post_id: @post.id)), method: :delete, remote: true do
-#       = icon('fas','heart')
-# - else
-#   #unlike
-#     = link_to post_likes_path(@post,current_user.likes.build),method: :post, remote: true do
-#       = icon('far','heart')


-# -if user_signed_in? 
-#   -if @post.like_user(current_user.id)
-#     = button_to "/posts/#{@post.id}/likes", id: "like-button", method: :delete, remote: true do
-#       = icon('fas','heart')
-#       %span
-#         = @post.like_count
-#   - else
-#     = button_to "/posts/#{@post.id}/likes", id: "like-button", method: :post, remote: true do
-#       = icon('far','heart')
-#       %span
-#         = @post.like_count
-# -else
-#   = icon('far','heart')
-#   -# -if likes.any?
-#   %span0p
-#     = @post.like_count

-if current_user.likes.find_by(post_id: @post.id)
  #liked
    = link_to post_like_path(@post, current_user.likes.find_by(post_id: @post.id)), method: :delete, remote: true do
      = icon('fas', 'heart')
    %span
      -# = @post.like_count
      -# = @likes_count

-else
  #like
    = link_to post_likes_path(@post,current_user.likes.build), method: :post, remote: true do
      = icon('far', 'heart')
    %span
      -# = @post.like_count
      -# = @likes_count

app/views/likes/create.js.erb
$("#like").html("<%= escape_javascript(render('likes/like')) %>");

app/views/likes/destroy.js.erb
$("#liked").html("<%= escape_javascript(render('likes/like'))%>");