config/routes.rb
Rails.application.routes.draw do
    # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  devise_for :users
  root to: "posts#index"

  resources :users, only:[:show]

  get 'messages' => 'messages#new'
  post 'messages' => 'messages#create'
  # post 'post/:post_id/likes' => 'likes#create'
  # delete 'post/:post_id/likes' => 'likes#destroy'

  resources :posts do 
    resources :comments, only: [:create, :destroy]
    resources :likes, only: [:create, :destroy]
    collection do
      get 'search'
      get 'place'
      get 'map'
      get 'word'
      get 'about'
    end
  end


  # devise_for :users, :controllers => {
  #   :registrations => 'users/registrations',
  #   :sessions => 'users/sessions'   
  # } 

  # devise_scope :user do
  #   get "sign_in", :to => "users/sessions#new"
  #   get "sign_out", :to => "users/sessions#destroy" 
  # end
end

app/views/shared/_comments.html.haml
-if @comments.any?
  .posts__comments--top
    -# .posts__comments--top__title
    %p
      = icon('far','comment-dots')
      %span コメント
    -@comments.each do |c|
      -# -if @comments.blank?
      .posts__comments--top__box
        .name
          = c.user.username unless c.user.blank?
          -# =link_to user_path(@user) do
          -#   = insert_name(@comments.user.username)
        .comment
          = c.content

  -if @post.user_id != current_user.id
    .posts__comments--bottom
      = form_for [@post, @comment] do |f|
        = f.hidden_field :post_id, value: @post.id
        = f.text_area :content, id: "text"
        %br
        = f.submit "投稿する", class: "comment-submit", id: "comment-submit"

app/views/shared/_each.html.haml
-@posts.each do |p|
  .each
    = link_to post_path(p.id) do
      = image_tag(p.image_url)

app/views/shared/_footer.html.haml
%footer
  .footer__left
    %p OnBoard
    -# = link_to '/' do
    -#   = icon("fab", "twitter-square")
    -# = link_to '/' do
    -#   = icon("fab", "facebook-square")


  .footer__right
    = link_to '/messages' do
      = icon("far", "envelope")

    = link_to '/posts/about' do
      = icon("fas", "id-card")

app/views/shared/_header.html.haml
%header
  .home
    = link_to "OnBoard", "/", data: {"turbolinks"=>false}

  %ul.menu
    -# %li.header__new
    -#   = link_to "New", "/posts/place", data: {"turbolinks"=>false}
    %li.menu__post
      =link_to "Post", "/posts/new", data: {"turbolinks"=>false}
    %li.menu__search
      = link_to "Search", "/posts/search", data: {"turbolinks"=>false}
    -if user_signed_in?
      %li.menu__mypage
        = link_to "My page",user_path(@user, id: current_user.id), data: {"turbolinks"=>false}
      %li.menu__logout
        = link_to "Log out", "/users/sign_out", method: :delete, data: {"turbolinks"=>false}
    -else
      %li.menu__signup
        = link_to "Sign up", "/users/sign_up", data: {"turbolinks"=>false}

      %li.menu__login
        = link_to "Log in", "/users/sign_in", data: {"turbolinks"=>false}

app/views/shared/_mypost.html.haml
-@posts.each do |p|
  .mypost
    = link_to post_path(p.id) do
      = image_tag(p.image.url)

app/views/shared/_newpost.html.haml
-@posts.each do |p|
  .newitem
    = link_to post_path(p.id) do
      = image_tag(p.image.url)

app/views/shared/_other__posts.html.haml
-if @post.user.id != current_user.id
  .posts__other--slick
    -# =link_to user_path(@user) do
    -#   =insert_name(@post.user.username)
    -# = @post.user.username
    -# %span さん
    -# %br
    %span その他の投稿
    %ul.posts__other--slick__slide
      -@posts.each do |f|
        -# .other__image
        %li.other__image
          = link_to post_path(f.id) do
            = image_tag(f.image.url)
-else
  .posts__other--others
    %span#notmine その他の投稿
  %ul.other
    -@others.each do |f|
      %li.other__image
        = link_to post_path(f.id) do
          = image_tag(f.image.url)

  -#   =link_to user_path(@user) do
  -#     =insert_name(@post.user.username)
  -#   -# = @post.user.username
  -#   %span さん
  -#   %br

app/views/shared/_posts__mainleft.html.haml
.posts__main--left__top
  =image_tag @post.image.url
.posts__main--left__middle
  %p
    = @post.title
  %table
    %tr
      %td.question 国：
      %td.answer
        =@post.country
      %td.question 都市：
      %td.answer
        = @post.city
      %td 撮影方法：
      %td
        = @post.how


.posts__main--left__bottom
  = @post.discription

.posts__main--left__option
  -if @post.user.id == current_user.id
    .posts__main--left__option#button
      = link_to "この投稿を編集する", edit_post_path(@post), method: :get, class: "edit-button"
      = link_to "この投稿を削除する", post_path(@post), method: :delete, class: "delete-button"

  -else
    .posts__main--left__option#like-heart
      %p この投稿が気に入ったら
      %p ♡を押してね
      %br/
      = render "likes/like", locals: { post: @post, posts: @posts, likes: @likes, like: @like }

app/views/shared/_posts__mainparts.html.haml
.posts__main--top
  .country
    %p 国名
    %span :
    .text
      = @post.country
  .city
    %p 都市名
    %span :
    .text
      = @post.city
  .how
    %p 撮影方法
    %span :
    .text
      = @post.how
.posts__main--middle
  =image_tag @post.image.url
.posts__main--bottom
  = @post.discription

-# .ownpost
-#   .ownpost-one
-#     .left
-#       =image_tag @post.image.url

-#     .right
-#       .right__top
-#         .title
-#           %p
-#             = @post.title
-#       .right__details
-#         .country
-#           %p 国名
-#           %span :
-#           -# = Country.find(@post.country_id)&.name
-#           -# = @post.country
-#         .city
-#           %p 都市名
-#           %span :
-#           = @post.city
-#         .how
-#           %p 撮影方法
-#           %span :
-#           = @post.how

-#       .right__discription
-#         = @post.discription

app/views/shared/_posts__mainright.html.haml
.posts__main--right__intro
  .name
    %span ID:
    =link_to user_path(@user) do
      =insert_name(@post.user.username)
    -# %span さんの投稿
  .info
    %p よく使用する撮影機器
    .answer
      = @user.fav_cam
  .pic
    %p よく撮影する被写体
    .answer
      = @user.fav_pic
  .countries
    %p 好きな旅行先
    .answer
      = @user.fav_country
      
.posts__main--right__details
  .country
    %p 国：
    .text
      = @post.country
  .city
    %p 都市：
    .text
      = @post.city
  .how
    %p 撮影方法：
    .text
      = @post.how

-if @post.user.id == current_user.id
  .posts__main--right__choice
    = link_to "この投稿を編集する", edit_post_path(@post), method: :get, class: "edit-button"
    %br/
    %br/
    = link_to "この投稿を削除する", post_path(@post), method: :delete, class: "delete-button"

-else
  .posts__main--right__like
    %p この投稿が気に入ったら
    %p ♡を押してね
    %br/
    = render "likes/like", locals: { post: @post, posts: @posts, likes: @likes, like: @like }

app/views/shared/_ranking.html.haml
%p Ranking
%br
.ranking-order
  -@rank.each.with_index(1) do |post, i|
    .ranking-order__box
      .box-each
        .box-each__rank
          = icon('fas', 'crown')
          %span No.#{i}
        = link_to post_path(post.id) do
          = image_tag(post.image.url)